/*
 * Acerca.java
 *
 * Created on 24 de diciembre de 2007, 03:09 PM
 */

/**
 *
 * @author  Usuaio
 */
public class Acerca extends javax.swing.JFrame {
    
    /** Creates new form Acerca */
    public Acerca() {
        initComponents();
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("JConsolidado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 30, 130, 17);

        jLabel3.setText("Versión 2.0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 60, 80, 14);

        jLabel4.setText("Plataforma: Java 1.6.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 90, 180, 14);

        jLabel5.setText("IDE: NetBeans 6.1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 120, 110, 14);

        jLabel6.setText("Tipo: Freeware");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 150, 250, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/java_logo.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 30, 60, 100);

        jLabel8.setText("Fecha de creación: Martes, 26 de Febrero del 2008");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 180, 290, 14);

        jLabel9.setText("Actualizado: Domingo, 24 de Agosto del 2008");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 200, 250, 30);

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Derechos Reservados @ 2008");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 10, 370, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ChicoSoft");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 30, 370, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 260, 370, 60);

        jProgressBar1.setIndeterminate(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 320, 440, 14);

        jLabel12.setText("Producto Hecho en Nicaragua por ChicoSoft");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 234, 250, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-433)/2, (screenSize.height-362)/2, 433, 362);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
